
// This file is automatically generated. Do not modify it manually.
export const firebaseConfig = {
  "apiKey": "mock-api-key",
  "authDomain": "course-registration-cce07.firebaseapp.com",
  "projectId": "course-registration-cce07",
  "storageBucket": "course-registration-cce07.appspot.com",
  "messagingSenderId": "654374337674",
  "appId": "1:654374337674:web:80325498a67a0c4b26cac8"
};

